services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    command: python src/main.py
    volumes:
      - .:/app

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_URL=redis://redis:6379/0


  celery_worker:
    build: .
    container_name: celery_worker
    env_file:
      - .env
    depends_on:
      - redis
      - fastapi
    command: celery -A src.celery_config worker --loglevel=info --queues song_queue,user_queue
    volumes:
      - .:/app