services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    command: uvicorn src.main:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - .:/app

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"


  celery_worker:
    build: .
    container_name: celery_worker
    env_file:
      - .env
    depends_on:
      - redis
      - fastapi
    command: celery -A src.celery_config worker --loglevel=info --queues song_queue,user_queue --max-tasks-per-child=10
    volumes:
      - .:/app