services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    command: celery -A app.celery_worker.celery worker --loglevel=info
    depends_on:
      - redis
      - fastapi-app
    environment:
      - REDIS_URL=redis://redis:6379/0
